server:
  port:8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


datasource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/BackeendProject1?useUnicode=true&characterEncoding=UTF-8
