server:
  port:8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    username: ajy8u9cn1h4pohh9e4pi
    password: ajy8u9cn1h4pohh9e4pi
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gcp.connect.psdb.cloud:3306/hunsd
